name: CI/CD FastAPI a Azure Container Apps

on:
  push:
    branches:
      - deployment
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP: 'portafolio-2025'
  AZURE_CONTAINER_APP: 'backend-fastapii-deploy'
  ACR_LOGIN_SERVER: 'backendescnil994.azurecr.io'
  ACR_REPOSITORY: 'backend-fastapi'
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read 

    steps:
      - name: Checkout del CÃ³digo
        uses: actions/checkout@v3

      # === ETAPA 1: BUILD & PUSH ===
      - name: Login en Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Login en ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Construir y Subir Imagen
        uses: docker/build-and-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.ACR_LOGIN_SERVER }}/${{ env.ACR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          
      # === ETAPA 2: DEPLOY ===
      - name: Deploy a Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: ${{ env.AZURE_CONTAINER_APP }}
          resourceGroup: ${{ env.AZURE_RESOURCE_GROUP }}
          imageToDeploy: ${{ env.ACR_LOGIN_SERVER }}/${{ env.ACR_REPOSITORY }}:${{ env.IMAGE_TAG }}