name: Deploy to Azure Container Apps

on:
  push:
    branches: [ deployment ]
  workflow_dispatch:

env:
  RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  CONTAINER_APP_NAME: ${{ secrets.AZURE_CONTAINER_APP_NAME }}
  CONTAINER_APP_ENV: portafolio-env

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

      # === ETAPA 1: BUILD & PUSH ===
      - name: Login en Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Login en ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Construir y Subir Imagen
        uses: docker/build-and-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.ACR_LOGIN_SERVER }}/${{ env.ACR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          
      # === ETAPA 2: DEPLOY ===
      - name: Deploy a Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: ${{ env.AZURE_CONTAINER_APP }}
          resourceGroup: ${{ env.AZURE_RESOURCE_GROUP }}
          imageToDeploy: ${{ env.ACR_LOGIN_SERVER }}/${{ env.ACR_REPOSITORY }}:${{ env.IMAGE_TAG }}